import Footer from '../../../component/footer/page';
import Mainheader from '../../../component/mainheader/page';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ display: 'flex', flexDirection: 'column', margin: '0%' }}>
        <Mainheader />
        <div style={{ height: '200px', width: '990px' }}></div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
